In [1]:
# Data wangling is the process of taking messy data and transforming it into an organize format
#The superpower of data wangling is data filtering which is very important in
# ...machine learning workflow
# scope and focus can be easily distracted
#filtering allow us to remove logical impossibilities
# targetted slicing, by extracting out only the dataset needed

In [6]:
# dataset : Nigerian nursing mothers
# Scenario 1:
#we want to know the health challenges faced by the poorest mothers living in rural area
# to import google drive
from google.colab import drive
drive.mount('/content/drive')
# package of interest
import pandas as pd

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [8]:
# upload the dataset of interest
health_data = pd.read_csv('/content/drive/MyDrive/2nd Semester/Datasets/nigeria_nursing_mothers_healthcare.csv')
health_data.head()

,Geopolitical_Zone,Residence,Wealth_Quintile,Education_Level,Skilled_Birth_Attendance,Facility_Delivery,Exclusive_Breastfeeding,Full_Immunization,Distance_to_Facility_km
0,North East,Rural,Middle,Primary,1,1,1,0,9.35
1,South East,Urban,Richest,Higher,1,1,1,1,1.99
2,North Central,Urban,Richer,Primary,1,1,0,0,0.95
3,North Central,Rural,Poorest,Primary,1,1,0,0,15.22
4,North East,Urban,Richer,Secondary,1,0,1,0,1.10

In [9]:
# create a new dataset from the existing one ( called subsetting )
targeted_mothers = health_data[(health_data['Residence'] == 'Rural') & (health_data['Wealth_Quintile'] == 'Poorest')]

In [10]:
print(f"original dataset size:", len (health_data))
print(f"New dataset size:", len(targeted_mothers))

original dataset size: 10000
New dataset size: 1866

In [25]:
unemployment_data = pd.read_csv('/content/drive/MyDrive/2nd Semester/Datasets/nigeria_unemployment_missing_data.csv')
unemployment_data.head()

,Age,Gender,Region,Location,Education_Level,Employment_Status,Years_Of_Experience,Monthly_Income_NGN
0,53,Male,North West,Urban,NaN,Employed,37.0,84220.84
1,43,Female,South West,Urban,Primary,Employed,24.0,69911.72
2,29,Female,South South,Rural,NaN,Underemployed,NaN,31096.21
3,57,Female,South West,Rural,Primary,Employed,42.0,108994.91
4,22,Female,South South,Rural,NaN,Underemployed,5.0,31807.56

In [34]:
# To check for missing values
import pandas as pd
unemployment_data.isnull().sum()

Age                       0
Gender                    0
Region                  250
Location                  0
Education_Level        1127
Employment_Status         0
Years_Of_Experience     500
Monthly_Income_NGN      408
dtype: int64

In [35]:
unemployment_data.shape

(5000, 8)

In [38]:
# to preserve the original data while we edited another copy
unemployment_data_1 = unemployment_data.copy()
unemployment_data_1.head()

,Age,Gender,Region,Location,Education_Level,Employment_Status,Years_Of_Experience,Monthly_Income_NGN
0,53,Male,North West,Urban,NaN,Employed,37.0,84220.84
1,43,Female,South West,Urban,Primary,Employed,24.0,69911.72
2,29,Female,South South,Rural,NaN,Underemployed,NaN,31096.21
3,57,Female,South West,Rural,Primary,Employed,42.0,108994.91
4,22,Female,South South,Rural,NaN,Underemployed,5.0,31807.56

In [42]:
# To take away all the missing values
unemployment_data_1.dropna(inplace=True)
# to get the new size of the data
unemployment_data_1.shape

(3018, 8)

In [44]:
# to fix the years of experience columns with the average years of experience
# calculate the average years of experience
average_experience = unemployment_data['Years_Of_Experience'].mean()
average_experience

np.float64(21.835333333333335)